openapi: "3.0.2"
info:
  title: Microservice B
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /:
    get:
      summary: Hello World endpoint
      operationId: helloWorld
      tags:
        - helloWorld
      responses:
        '200':
          description: Hello World String
          content:
            application/json:
              schema:
                type: string
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Error:
      type: object
      properties:
        timestamp:
          type: string
          description: The date and time when the error occurred in ISO 8601 format.
          format: date-time
          example: "2024-01-04T15:30:00Z"
        session:
          type: string
          format: uuid
          description: A unique UUID for the session instance where the error happened, useful for tracking and debugging purposes.
        error:
          type: string
          description: A brief error message or identifier.
        message:
          type: string
          description: A detailed error message.
        path:
          type: string
          description: The path that resulted in the error.