apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-b
  name: microservice-b
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-b
  template:
    metadata:
      labels:
        app: microservice-b
    spec:
      containers:
      - image: pollitodev/spring-cloud-v2-microservice-b:0.1.0-SNAPSHOT
        name: spring-cloud-v2-microservice-b
kube
        securityContext:
          capabilities:
            drop:
              - NET_RAW
        volumeMounts:
        - name: config-volume
          mountPath: /config
          readOnly: true
        env:
          - name: SPRING_CONFIG_ADDITIONAL-LOCATION
            value: "file:/config/"
      volumes:
      - name: config-volume
        configMap:
          name: microservice-b
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-b
  name: microservice-b
  namespace: default
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: microservice-b
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservice-b
  namespace: default
data:
  application.properties: |-
    eureka.client.serviceUrl.defaultZone=http://naming-server:8761/eureka/
